const testJSON = {
  "categoryNavigation": {
    "categoryArray":[  
       {  
          "name":"Rooms",
          "uniqueid":"10001",
          "isleafnode":"N",
          "url":"",
          "seourl":"",
          "image":"",
          "shortdescription":"",
          "subCategoryArray":[  
             {  
                "name":"Living Room",
                "uniqueid":"10002",
                "isleafnode":"Y",
                "url":"/clp/10002",
                "seourl":"",
                "image":"",
                "shortdescription":""
             },
             {  
                "name":"Bedroom",
                "uniqueid":"10003",
                "isleafnode":"Y",
                "url":"/clp/10003",
                "seourl":"",
                "image":"",
                "shortdescription":""
             }
          ]
       },
       {  
          "name":"Products",
          "uniqueid":"10005",
          "isleafnode":"N",
          "url":"",
          "seourl":"",
          "image":"",
          "shortdescription":"",
          "subCategoryArray":[  
             {  
                "name":"Sofas",
                "uniqueid":"10006",
                "isleafnode":"Y",
                "url":"/plp/10006",
                "seourl":"",
                "image":"",
                "shortdescription":""
             },
             {  
                "name":"Recliners",
                "uniqueid":"10007",
                "isleafnode":"Y",
                "url":"/plp/10007",
                "seourl":"",
                "image":"",
                "shortdescription":""
             },
             {  
                "name":"Chairs",
                "uniqueid":"10008",
                "isleafnode":"Y",
                "url":"/plp/10008",
                "seourl":"",
                "image":"",
                "shortdescription":""
             },
             {  
                "name":"Stools",
                "uniqueid":"10009",
                "isleafnode":"Y",
                "url":"/plp/10009",
                "seourl":"",
                "image":"",
                "shortdescription":""
             },
             {  
                "name":"Dining Set",
                "uniqueid":"10010",
                "isleafnode":"Y",
                "url":"/plp/10010",
                "seourl":"",
                "image":"",
                "shortdescription":""
             },
             {  
                "name":"Tables",
                "uniqueid":"10011",
                "isleafnode":"Y",
                "url":"/plp/10011",
                "seourl":"",
                "image":"",
                "shortdescription":""
             }
          ]
       }
    ]
}
 };
  module.exports = testJSON;
  